import {supabase} from './supabase-client.js';
const frame=document.querySelector('#panel');
const money=n=>'R$ '+Math.round(Number(n||0)).toLocaleString('pt-BR'),pct=n=>(Number(n||0)*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%',names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],abbr=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];
async function patch(doc){const screen=doc.querySelector('[data-screen-label^="Ano "]');if(!screen)return;const year=Number((screen.getAttribute('data-screen-label')||'').match(/\d{4}/)?.[0]||new Date().getFullYear()),{data,error}=await supabase.rpc('resumo_ano',{p_ano:year});if(error)throw error;const rows=(data||[]).map((x,i)=>({...x,i,meta:Number(x.meta||0),real:Number(x.realizado||0),pct:Number(x.pct||0)})),used=rows.filter(x=>x.meta||x.real),tm=used.reduce((a,x)=>a+x.meta,0),tr=used.reduce((a,x)=>a+x.real,0),hits=used.filter(x=>x.bateu).length,gap=Math.max(tm-tr,0);
 const kpiGrid=screen.firstElementChild,cards=kpiGrid?[...kpiGrid.children]:[];const values=[[money(tm),`${used.length} meses lançados`],[money(tr),tm?pct(tr/tm)+' da meta':'—'],[`${hits} de ${used.length}`,hits?'meses com meta atingida':'nenhum mês batido'],[money(gap),'a recuperar até dezembro']];cards.slice(0,4).forEach((c,i)=>{const parts=[...c.children];if(parts[1])parts[1].textContent=values[i][0];if(parts[2])parts[2].textContent=values[i][1]});
 const chartTitle=[...screen.querySelectorAll('h2')].find(h=>(h.textContent||'').trim()==='Meta × realizado por mês'),chartCard=chartTitle?.parentElement?.parentElement,chartArea=chartCard?[...chartCard.children].find(c=>(c.style?.height||'')==='210px'):null;if(chartArea){const max=Math.max(...rows.map(x=>Math.max(x.meta,x.real)),1);chartArea.innerHTML=rows.map(x=>`<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:9px;min-width:0"><div style="display:flex;align-items:flex-end;gap:3px;height:160px"><div style="width:11px;border-radius:4px 4px 0 0;background:#E1EBE9;height:${Math.round(x.meta/max*160)}px"></div><div style="width:11px;border-radius:4px 4px 0 0;background:${x.bateu?'#05918C':x.pct>.9?'#E890A2':'#CD4664'};height:${Math.round(x.real/max*160)}px"></div></div><div style="font:600 10px/1 Manrope,sans-serif;color:#8D9997">${abbr[x.i]}</div></div>`).join('')}
 const tableTitle=[...screen.querySelectorAll('h2')].find(h=>(h.textContent||'').trim()==='Fechamento mês a mês'),tableCard=tableTitle?.parentElement;if(tableCard){const header=[...tableCard.children].find(c=>(c.textContent||'').includes('Meta 1')&&(c.textContent||'').includes('Realizado'));if(header){let n=header.nextElementSibling;while(n){const z=n.nextElementSibling;n.remove();n=z}for(const x of used){const row=doc.createElement('div');row.style.cssText='display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr) minmax(0,1fr) minmax(0,.8fr);gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #F6F9F8';row.innerHTML=`<div style="font:700 12.5px/1 Manrope,sans-serif">${names[x.i]}</div><div style="text-align:right;white-space:nowrap;font:500 12px/1 'JetBrains Mono',monospace;color:#8D9997">${Math.round(x.meta).toLocaleString('pt-BR')}</div><div style="text-align:right;white-space:nowrap;font:500 12px/1 'JetBrains Mono',monospace">${Math.round(x.real).toLocaleString('pt-BR')}</div><div style="text-align:right;white-space:nowrap;font:700 12px/1 'JetBrains Mono',monospace;color:${x.bateu?'#05918C':x.pct>.9?'#E890A2':'#CD4664'}">${x.meta?pct(x.pct):'—'}</div>`;tableCard.appendChild(row)}}}}
async function wire(){const doc=frame.contentDocument;if(!doc?.body)return;setTimeout(()=>patch(doc).catch(console.error),250);doc.addEventListener('click',e=>{const t=(e.target.closest('div,span')?.textContent||'').trim();if(/^Ano \d{4}$/.test(t))setTimeout(()=>patch(doc).catch(console.error),220)},true)}
frame.addEventListener('load',()=>wire().catch(console.error));
